### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by Guite** [andstor/copycat-action#19]
Hello,

we (@craigh and me) are trying to use this action, but weren't successful yet.

First we had some errors like `fatal: could not read Password for 'https://***@github.com': No such device or address` which was probably caused by the token had not being setup correctly.

The current state is:

1. I created a personal access token (at my account) and added it as secret to the repository which runs the action (owned by an organisation).
2. The workflow looks like this: https://github.com/zikula/core/blob/master/.github/workflows/copy-to-dist.yml
3. The action execution can be seen here: https://github.com/zikula/core/runs/492015952
4. Current error message: `fatal: unable to access 'https://': Could not resolve host: info` `Cloning 'zikula/core' failed`.

We are a bit lost here and can only do "try and error". Can you give us an advice?

**Comment by andstor** [comment]
Hello!
Glad you want to use my action 😊

This issue was quite the challenge!
However, I think I have found the root of your problem.

It seems you have simply included a space in your personal access token secret.
Removing the secret and re-adding it (without the space) should resolve your issue!

**Comment by Guite** [comment]
> It seems you have simply included a space in your personal access token secret.

Something like that it was indeed!

Thank you very much! It works.
