### ISSUE TITLE
Add option to delete all before push

### ISSUE THREAD

**Issue by Casperhr** [andstor/copycat-action#21]
I often have issue, if I rename, move folder, or delete a file. It's not removed from where I copy them to. 
Is there a solution for this already? Else maybe a simple "clean" option could be added which deletes the folder first?

**Comment by andstor** [comment]
Hi Casper!

The main purpose of this action is to provide support for **copying** files to a repository. Hence, the behavior you describe has been (more or less) intentional.

However, I see that a cleaning functionality could be useful. I will add a flag for clearing all files in the **dst_path**. Stay tuned 📻 😄

**Comment by andstor** [comment]
Hi,
i have now released a new version of Copycat, [v3](https://github.com/andstor/copycat-action/releases/tag/v3). Note that it is a `major` version update ([v3.0.0](https://github.com/andstor/copycat-action/releases/tag/v3.0.0)) as it is not backwards compatible (mainly renamed input variables). See the [CHANGELOG.md](https://github.com/andstor/copycat-action/blob/master/CHANGELOG.md).

By setting the new `clean` input variable to `true`, all files under the `dst_path` will be deleted before copying new files over.

**Comment by Casperhr** [comment]
Great thanks, will test it now

**Comment by Casperhr** [comment]
@andstor I think we have spoken about this, but can't find it now. So reopening this

If I have 2 repos copy into 1 repo

repo1/* -> repo3/somefolder/repo1/*
repo2/* -> repo3/somefolder/repo2/*

And using clean mode, then they will delete each others folder. Is it deleting subfolders?

**Comment by andstor** [comment]
When activating the `clean` mode, the file(s) in the destination path `dst_path` will be deleted before copying the file(s) over.

That is, if the destination path is a **directory**, all files under that directory are deleted, including files in subfolders.  However, if the destination path points to a single **file**, only that particular file will be deleted.

So, if you have:

1. `repo1/. -> repo3/somefolder/repo1/.`

2. `repo2/. -> repo3/somefolder/repo2/.`

> And using clean mode, then they will delete each others folder?

1\. will delete `repo1` and 2\. will delete `repo2`.
However, 1\. will not touch anything inside `repo2`, and 2 won't touch `repo1`.

If you want 1\. and/or 2\. to also delete everything inside the `somefolder`, then you hack it together by just skipping the last `/.` in the destination path (assuming a folder is copied).

> Is it deleting subfolders?

Yes.

**Comment by Casperhr** [comment]
So destination folder should end on /. and it wont do it?

**Comment by andstor** [comment]
> So destination folder should end on /. and it wont do it?

Yes. Specifying a `/` or `/.` at the end of a path indicates that it is a folder. If cleaning is active, then only that folder will be emptied, not any parent folders.

**Comment by Casperhr** [comment]
Thanks a lot
