### ISSUE TITLE
Overriding COMMIT_MESSAGE 

### ISSUE THREAD

**Issue by huksley** [andstor/copycat-action#28]
Please consider adding an option to specify different COMMIT_MESSAGE in configuration

**Comment by andstor** [comment]
Hi!
I have now added a `commit_message` input variable in the latest version ([v3.1.0](https://github.com/andstor/copycat-action/releases/tag/v3.1.0)).
This lets you specify a custom commit message 😄

**Comment by huksley** [comment]
Thank you! It works 👍
