### ISSUE TITLE
Copy files to a different branch of the same repository

### ISSUE THREAD

**Issue by anfederico** [andstor/copycat-action#44]
Based on the documentation it seems this would be possible.

[This](https://github.com/anfederico/rpkgs/blob/master/.github/workflows/cprmdf.yml) doesn't seem to work though. Any suggestions? Each push I'd like to copy the README_files from the master to the gh-pages branch.

**Comment by anfederico** [comment]
Ah, solved through the gh-pages action.

**Comment by henryzt** [comment]
Same here, it gives `fatal: destination path '<repo-name>' already exists and is not an empty directory.` error every time. I assume it is because the name collides with the source repo folder which is already cloned.
