### ISSUE TITLE
[FEATURE REQUEST] Copy from GitHub Action Workspace to the repo's branch

### ISSUE THREAD

**Issue by fariskamaludin-skymind** [andstor/copycat-action#52]
Is there any way that we can copy files/folders from the the GitHub Workspace into one of the repo's branches?

**Comment by ComplexImg** [comment]
> Is there any way that we can copy files/folders from the GitHub Workspace into one of the repo's branches?

You can just clone a repo that you need in GitHub actions and then copy what you need. I had similar issue and did it the next way:

```
      - name: Copy docs to the lib
        run: |
          git clone https://<token>@github.com/repo.git
          cp repo/file.pdf packages/lib/
           ...
          rm -rf repo
```

Maybe it helps you :)

**Comment by fariskamaludin-skymind** [comment]
> > Is there any way that we can copy files/folders from the GitHub Workspace into one of the repo's branches?
> 
> You can just clone a repo that you need in GitHub actions and then copy what you need. I had similar issue and did it the next way:
> 
> ```
>       - name: Copy docs to the lib
>         run: |
>           git clone https://<token>@github.com/repo.git
>           cp repo/file.pdf packages/lib/
>            ...
>           rm -rf repo
> ```
> 
> Maybe it helps you :)

nice, thanks 👍
