### ISSUE TITLE
fatal: could not read Password for 'https://***@github.com': No such device or address

### ISSUE THREAD

**Issue by pilotkid** [andstor/copycat-action#53]
Hello, I cannot get it to work. What I am trying to accomplish is copying the changelog from one repo into another, within an organization. I have ensured that my PAT does not have a space in it, and I have tried both `${{ secrets.GITHUB_TOKEN }}`, and my PAT with all permissions granted. 

Any ideas?

**Comment by pilotkid** [comment]
I misspelled my repo name.

**Comment by prein** [comment]
I can confirm that misspelling the branch name will result in the same misleading error message (`could not read Password for 'https://***@github.com': No such device or address`).
